# Generated by Django 4.2 on 2023-11-27 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Categories', models.TextField(choices=[('Office supplies', 'OFFICE SUPPLIES'), ('Salares', 'SALARIES'), ('Minor_repairs', 'MINOR REPAIRS'), ('Resource_persons', 'RESOURCE PERSONS'), ('Project_funding', 'PROJECT FUNDING')], default=None)),
                ('Phone_number', models.IntegerField()),
                ('Bank_name', models.TextField(max_length=20)),
                ('Account_number', models.IntegerField()),
                ('Item_name', models.TextField(max_length=50)),
                ('Purpose', models.CharField(max_length=70)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Requisitions',
                'ordering': ['-Date'],
            },
        ),
    ]
