# Generated by Django 4.2 on 2023-11-28 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Req', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requisition',
            old_name='Name',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='requisition',
            name='Categories',
            field=models.TextField(choices=[('Office supplies', 'OFFICE SUPPLIES'), ('Salaries', 'SALARIES'), ('Minor_repairs', 'MINOR REPAIRS'), ('Resource_persons', 'RESOURCE PERSONS'), ('Project_funding', 'PROJECT FUNDING')], default=None),
        ),
    ]
