# Generated by Django 4.2 on 2023-11-29 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Req', '0002_rename_name_requisition_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requisition',
            options={'ordering': ['-Date'], 'permissions': [('can_approve_requisition', 'Can approve requisitions'), ('can_reject_requisition', 'Can reject requisitions')], 'verbose_name_plural': 'Requisitions'},
        ),
    ]
