# Generated by Django 4.2 on 2023-11-30 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Req', '0003_alter_requisition_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requisition',
            old_name='is_approved',
            new_name='approved',
        ),
    ]
