# Generated by Django 4.2.6 on 2023-12-18 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Req', '0004_rename_is_approved_requisition_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='Amount',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
    ]
